apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: koala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: koala
  template:
    metadata:
      labels:
        app: koala
    spec:
      containers:
      - name: koala
        image: fen9li/koala:v1
---
apiVersion: v1
kind: Service
metadata:
  name: koala-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30123
  selector:
    app: koala
